import { assertReadOnlySql } from '../../admin-os/lib/sql-templates/guard'
import type { SqlGenerationRequest, SqlGenerationResult } from './sql-generation-engine'
import { spawn } from 'node:child_process'

type VannaResponse = {
  sql?: string
  generated_sql?: string
  query?: string
  confidence?: number
  explanation?: string
  error?: string
}

function resolveVannaEndpoint(): string {
  const endpoint = process.env.VANNA_API_URL || process.env.VANNA_ENDPOINT || ''
  if (!endpoint) {
    throw new Error('VANNA_API_URL not configured')
  }
  return endpoint
}

function extractSql(payload: VannaResponse): string {
  const sql = payload.sql || payload.generated_sql || payload.query || ''
  if (!sql || typeof sql !== 'string') {
    throw new Error('Vanna response missing sql')
  }
  return sql
}

async function generateViaHttp(request: SqlGenerationRequest): Promise<SqlGenerationResult> {
  const endpoint = resolveVannaEndpoint()
  const resp = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      question: request.naturalQuery,
      schema: request.schemaInfo,
      query_type: request.queryType,
      max_rows: request.maxRows,
      task_id: request.taskId,
    }),
  })

  if (!resp.ok) {
    throw new Error(`Vanna provider error: ${resp.status} ${resp.statusText}`)
  }

  const payload = (await resp.json()) as VannaResponse
  if (payload.error) {
    throw new Error(payload.error)
  }
  const sql = extractSql(payload)
  assertReadOnlySql(sql)

  return {
    sql,
    confidence: typeof payload.confidence === 'number' ? payload.confidence : 0.7,
    explanation: payload.explanation || 'Generated by Vanna SQL provider',
    used_examples: [],
  }
}

async function generateViaSubprocess(request: SqlGenerationRequest): Promise<SqlGenerationResult> {
  const pythonBin = process.env.PYTHON_BIN || 'python3'
  const scriptPath =
    process.env.VANNA_SUBPROCESS_SCRIPT ||
    `${process.cwd()}/server-actions/capabilities/vanna_subprocess_runner.py`

  const payload = JSON.stringify({
    question: request.naturalQuery,
    schema: request.schemaInfo,
    query_type: request.queryType,
    max_rows: request.maxRows,
    task_id: request.taskId,
  })

  const result = await new Promise<VannaResponse>((resolve, reject) => {
    const child = spawn(pythonBin, [scriptPath], {
      stdio: ['pipe', 'pipe', 'pipe'],
      env: {
        ...process.env,
      },
    })

    let stdout = ''
    let stderr = ''
    const timeoutMs = Number.parseInt(process.env.VANNA_SUBPROCESS_TIMEOUT_MS || '20000', 10)
    const timeout = setTimeout(() => {
      child.kill('SIGKILL')
      reject(new Error('Vanna subprocess timeout'))
    }, timeoutMs)

    child.stdout.on('data', (chunk) => {
      stdout += chunk.toString()
    })
    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString()
    })
    child.on('error', (err) => {
      clearTimeout(timeout)
      reject(err)
    })
    child.on('close', (code) => {
      clearTimeout(timeout)
      if (code !== 0) {
        reject(new Error(stderr || `Vanna subprocess exited with code ${code}`))
        return
      }
      try {
        const parsed = JSON.parse(stdout.trim())
        resolve(parsed)
      } catch (err) {
        reject(new Error(`Vanna subprocess invalid JSON: ${err instanceof Error ? err.message : String(err)}`))
      }
    })

    child.stdin.write(payload)
    child.stdin.end()
  })

  if (result.error) {
    throw new Error(result.error)
  }
  const sql = extractSql(result)
  assertReadOnlySql(sql)

  return {
    sql,
    confidence: typeof result.confidence === 'number' ? result.confidence : 0.7,
    explanation: result.explanation || 'Generated by Vanna subprocess',
    used_examples: [],
  }
}

export async function generateSqlWithVanna(request: SqlGenerationRequest): Promise<SqlGenerationResult> {
  const mode = String(process.env.VANNA_MODE || '').toLowerCase()
  if (mode === 'subprocess' || mode === 'local') {
    return generateViaSubprocess(request)
  }
  if (process.env.VANNA_API_URL || process.env.VANNA_ENDPOINT) {
    return generateViaHttp(request)
  }
  throw new Error('Vanna provider not configured. Set VANNA_MODE=subprocess or VANNA_API_URL.')
}
