#!/usr/bin/env python3
import json
import os
import sys
from typing import Any, Dict


def load_payload() -> Dict[str, Any]:
    raw = sys.stdin.read()
    if not raw:
        raise ValueError("empty payload")
    return json.loads(raw)


def resolve_vanna_src() -> str:
    explicit = os.getenv("VANNA_SRC_PATH")
    if explicit:
        return explicit
    # Default to the reference Vanna source shipped in MAXshot
    return "/Users/alexzheng/Documents/JOB/AI_Project/MAXshot/Knowledgebase/Reference_Projects/Database/vanna/src"


def build_vanna_instance():
    vanna_src = resolve_vanna_src()
    if vanna_src and vanna_src not in sys.path:
        sys.path.insert(0, vanna_src)

    try:
        from vanna.legacy.openai.openai_chat import OpenAI_Chat
        from vanna.legacy.chromadb.chromadb_vector import ChromaDB_VectorStore
    except Exception as err:
        raise RuntimeError(f"Vanna imports failed: {err}")

    class MyVanna(ChromaDB_VectorStore, OpenAI_Chat):
        def __init__(self, config=None):
            ChromaDB_VectorStore.__init__(self, config=config)
            OpenAI_Chat.__init__(self, config=config)

    api_key = os.getenv("VANNA_API_KEY") or os.getenv("OPENAI_API_KEY") or ""
    model = os.getenv("VANNA_MODEL") or os.getenv("OPENAI_MODEL") or "gpt-4o-mini"

    if not api_key:
        raise RuntimeError("Missing VANNA_API_KEY or OPENAI_API_KEY")

    config = {
        "api_key": api_key,
        "model": model,
    }
    return MyVanna(config=config)


def main() -> None:
    try:
        payload = load_payload()
        question = str(payload.get("question") or "").strip()
        schema = str(payload.get("schema") or "").strip()

        if not question:
            raise RuntimeError("question is required")

        vn = build_vanna_instance()

        # Optional: load schema (DDL) as training context
        if schema:
            vn.train(ddl=schema)

        sql = vn.generate_sql(question)
        if not sql:
            raise RuntimeError("Vanna returned empty SQL")

        out = {
            "sql": sql,
            "confidence": 0.7,
            "explanation": "Generated by Vanna legacy (subprocess)",
        }
        sys.stdout.write(json.dumps(out))
    except Exception as err:
        sys.stdout.write(json.dumps({"error": str(err)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
